# Generated by Django 5.0.2 on 2024-03-20 13:49

import MS1_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('ind', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=MS1_web.models.post)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to=MS1_web.models.pfp)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
