# Generated by Django 5.0.2 on 2024-03-20 11:00

import MS1_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS1_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('ind', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=MS1_web.models.post)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='entry',
        ),
    ]
